/* ===== Internationalization ===== */
const translations = {
    fr: {
        // Nav
        nav_home: "Accueil",
        nav_stories: "Histoires",
        nav_concepts: "Concepts",
        nav_what: "C'est quoi ?",
        nav_anatomy: "Anatomie",
        nav_live: "Modification Live",
        nav_animations: "Animations",
        nav_bezier: "Courbes de Bezier",
        nav_gallery: "Galerie",
        nav_workshop: "Atelier",
        nav_recipe: "Recette",
        // Workshop
        workshop_title: "Atelier SVG",
        workshop_subtitle: "Choisissez une illustration et modifiez ses variables CSS en direct",
        workshop_how_title: "Comment ca marche",
        workshop_how_desc: "Chaque SVG de la galerie declare ses parametres dans une regle <code>:root</code>, et accole un commentaire <code>/* @ws ... */</code> qui dit a l'atelier comment construire le bon controle. C'est tout. Le fichier reste un SVG valide ouvrable dans n'importe quel navigateur.",
        workshop_how_extra: "<strong>Compare</strong> place le SVG et la photo source cote a cote, <strong>Telecharger</strong> recupere ton SVG avec tes modifications, et <strong>Voir le code source</strong> sous l'illustration ouvre le fichier brut dans un nouvel onglet.",
        workshop_view_source: "Voir le code source \u2192",
        workshop_controls: "Controles",
        workshop_reset: "Reinitialiser",
        workshop_empty: "Ce SVG n'expose aucune variable.",
        workshop_view_svg: "SVG",
        workshop_view_compare: "Comparer",
        workshop_view_photo: "Photo",
        workshop_download: "Telecharger",
        workshop_editor_title: "Envie de pousser plus loin ?",
        workshop_editor_desc: "Cette page est une vitrine statique. Pour l'atelier complet, surveillance des fichiers, snapshots, import d'une photo de reference, metriques de ressemblance, clonez le depot et demarrez le serveur local :",
        workshop_editor_link: "Ouvrir l'editeur interactif \u2192",
        // Footer
        footer_made: "Fait par",
        // Home
        home_title: "Formation SVG",
        home_subtitle: "Decouvrez la puissance du SVG pour le web",
        home_pitch_title: "Le SVG, un outil sous-estime",
        home_pitch: `Le SVG est un outil precieux pour n'importe quel developpeur web. <a class="inline-link" href="what-is-svg.html">Optimise pour toutes les tailles d'ecran</a>, il offre une puissance et une elegance pixel-perfect. Mais pas seulement : d'une <a class="inline-link" href="live-demo.html">flexibilite incomparable</a>, il est capable de s'adapter a vos utilisateurs avec un <a class="inline-link" href="animations.html">minimum de JavaScript</a>.`,
        home_problem_title: "Seul probleme...",
        home_problem: `Sa complexite peut effrayer (jetez un oeil a <a class="inline-link" href="svg-anatomy.html">l'anatomie d'un path</a> ou aux <a class="inline-link" href="bezier.html">courbes de Bezier</a>) :`,
        home_solution: `Cette suite peut sembler abstraite pour un humain, mais heureusement, pas pour une IA, explorez <a class="inline-link" href="workshop.html">l'atelier</a> ou <a class="inline-link" href="gallery.html">la galerie</a> !`,
        home_cta: "Venez decouvrir ou redecouvrir ce format d'image, dans une courte presentation avec de multiples exemples, dont certains generes en live !",
        home_start: "Commencer l'exploration",
        home_concepts_pitch: "Tu preferes une vue d'ensemble avant de plonger ? Jette un oeil a la carte des concepts.",
        home_concepts_cta: "Voir la carte des concepts",
        // Concepts page
        concepts_title: "Carte des concepts",
        concepts_subtitle: "Une vue d'ensemble du parcours, chapitre par chapitre",
        concepts_explore: "Explorer",
        concepts_intro: "Chaque carte mene a la page qui developpe le sujet. Tu peux y aller dans l'ordre, ou piocher selon ce qui t'intrigue.",
        concepts_what_desc: "Vectoriel vs matriciel, et pourquoi ca change tout au zoom.",
        concepts_anatomy_desc: "ViewBox, formes primitives, balise <path>, stylisation.",
        concepts_live_desc: "Tweaker remplissage, contour, rotation et voir le code mis a jour.",
        concepts_anim_desc: "CSS keyframes, SMIL, stroke-dashoffset, morphing de path.",
        concepts_bezier_desc: "Quadratiques, cubiques, points de controle a glisser.",
        concepts_workshop_desc: "SVGs parametriques avec controles live (couleurs, tailles, modes).",
        concepts_gallery_desc: "Exemples : fleurs, os pas-a-pas, generations IA, aide-memoires.",
        concepts_recipe_desc: "Le format @ws pour faire tes propres SVGs parametriques compatibles avec l'atelier.",
        concepts_cta_recipe: "Cuisiner \u2192",
        concepts_cta_what: "Decouvrir \u2192",
        concepts_cta_anatomy: "Demonter \u2192",
        concepts_cta_live: "Essayer \u2192",
        concepts_cta_anim: "Animer \u2192",
        concepts_cta_bezier: "Plier \u2192",
        concepts_cta_workshop: "Bricoler \u2192",
        concepts_cta_gallery: "Feuilleter \u2192",
        // What is SVG
        what_title: "C'est quoi, un SVG ?",
        what_subtitle: "Comprendre la difference entre images vectorielles et matricielles",
        what_vector_title: "Image Vectorielle (SVG)",
        what_raster_title: "Image Matricielle (PNG/JPG)",
        what_zoom: "Zoomez pour voir la difference !",
        what_vector_desc: "Definie par des formules mathematiques. Chaque forme est decrite par des equations, ce qui permet un redimensionnement infini sans perte de qualite.",
        what_raster_desc: "Composee d'une grille de pixels. Chaque pixel a une couleur fixe. En zoomant, les pixels deviennent visibles et l'image parait floue.",
        what_advantages_title: "Avantages du SVG",
        what_adv1: "Scalable a l'infini sans perte de qualite",
        what_adv2: "Fichiers legers pour les formes simples",
        what_adv3: "Modifiable par CSS et JavaScript",
        what_adv4: "Animable nativement",
        what_adv5: "Accessible (texte indexable par les moteurs de recherche)",
        what_adv6: "Ideal pour les icones, logos, illustrations",
        what_when_title: "Quand utiliser le SVG ?",
        what_when_svg: "SVG : icones, logos, illustrations, graphiques, animations",
        what_when_raster: "PNG/JPG : photos, images complexes avec beaucoup de couleurs",
        what_ai_title: "Pourquoi le SVG plait a l'IA",
        what_ai_p1: "Un SVG, c'est du texte. Du XML lisible, structure, avec des noms d'attributs explicites (cx, fill, d...). Pour un grand modele de langage, c'est exactement le terrain ou il excelle : il manipule des tokens, pas des pixels.",
        what_ai_p2: `La meme image en PNG ne serait qu'un tableau opaque de pixels. Une IA peut <em>reconnaitre</em> ce qu'elle voit, mais ne peut pas la modifier de maniere precise. En SVG, elle peut ajouter une forme, changer une couleur, ajuster une <a class="inline-link" href="bezier.html">courbe</a>, ou meme generer toute l'image a partir d'une description.`,
        what_ai_p3: `Toutes les illustrations IA de la <a class="inline-link" href="gallery.html">galerie</a> ont ete produites de cette facon : un prompt, une reponse en texte SVG, directement utilisable dans le navigateur.`,
        // Anatomy
        anat_title: "Anatomie d'un SVG",
        anat_subtitle: "Comprendre la structure du code SVG",
        anat_structure_title: "Structure de base",
        anat_structure_desc: "Un SVG est un document XML avec un element racine <svg> et des elements enfants qui decrivent les formes.",
        anat_viewbox_title: "Le ViewBox",
        anat_viewbox_desc: "L'attribut viewBox definit le systeme de coordonnees interne du SVG. Il permet de creer des graphiques responsifs qui s'adaptent a n'importe quelle taille.",
        anat_shapes_title: "Formes de base",
        anat_shapes_desc: "SVG offre plusieurs formes primitives pour construire vos graphiques.",
        anat_path_title: "La balise Path",
        anat_path_desc: "L'element <path> est le plus puissant du SVG. Il peut dessiner n'importe quelle forme avec des commandes de deplacement.",
        anat_path_commands: `Commandes principales : M (deplacer), L (ligne), H (horizontal), V (vertical), <a class="inline-link" href="bezier.html">C (courbe cubique), Q (courbe quadratique)</a>, A (arc), Z (fermer)`,
        anat_path_ai: `<i class="fa-solid fa-robot" style="color:#9b59b6; margin-right:0.4rem;"></i><strong>Cote IA :</strong> ces commandes (<code>M</code>, <code>C</code>, <code>Q</code>, <code>L</code>...) sont exactement ce qu'un LLM ecrit quand on lui demande de dessiner. Une fleur, un coeur, un logo : tout devient une chaine de caracteres comme <code>d="M30,45 C30,45 10,30 10,18..."</code>. Pour aller plus loin, voir les <a class="inline-link" href="bezier.html">courbes de Bezier</a>.`,
        anat_styling_title: "Stylisation",
        anat_styling_desc: `Les elements SVG peuvent etre styles avec des attributs, du CSS inline, ou des feuilles de style externes. Combine avec des <strong>variables CSS</strong>, le meme SVG devient parametrable a la volee, c'est exactement ce que fait <a class="inline-link" href="workshop.html">l'atelier</a>.`,
        anat_cheatsheet: "Aide-memoire complet",
        // Live demo
        live_title: "Modification en direct",
        live_subtitle: "Modifiez les attributs SVG et voyez le resultat instantanement",
        live_shape_title: "Forme interactive",
        live_shape_desc: "Utilisez les controles ci-dessous pour modifier les proprietes de cette forme SVG en temps reel.",
        live_code_title: "Code genere",
        live_code_desc: "Le code SVG se met a jour automatiquement lorsque vous modifiez les controles.",
        live_fill: "Remplissage",
        live_stroke: "Contour",
        live_strokew: "Epaisseur",
        live_opacity: "Opacite",
        live_rotation: "Rotation",
        live_scale: "Echelle",
        live_radius: "Rayon",
        live_sides: "Cotes",
        live_shape: "Forme",
        live_circle: "Cercle",
        live_rect: "Rectangle",
        live_polygon: "Polygone",
        live_star: "Etoile",
        live_reuse_desc: `Un SVG peut definir des elements reutilisables avec <code>&lt;defs&gt;</code> et <code>&lt;use&gt;</code>. Combinez cela avec des variables CSS pour creer des composants personnalisables.`,
        live_reuse_ai: `<i class="fa-solid fa-robot" style="color:#9b59b6; margin-right:0.4rem;"></i><strong>Le pattern d'une app IA :</strong> ce que tu vois ici est exactement la recette qu'on retrouve dans une application augmentee a l'IA : un <em>template</em> SVG (l'os, sa forme) plus des <em>parametres</em> (couleurs, texte) qui peuvent venir d'un humain... ou d'un LLM. <a class="inline-link" href="workshop.html">L'atelier</a> pousse l'idee plus loin avec une galerie complete de SVGs parametriques.`,
        live_dog_name: "Nom du chien",
        live_color_dark: "Couleur sombre",
        live_color_light: "Couleur claire",
        live_text_color: "Couleur du texte",
        bezier_legend_start_end: "Depart / Fin",
        bezier_legend_control_point: "Point de controle",
        bezier_legend_curve: "Courbe",
        bezier_legend_cp1: "Point de controle 1",
        bezier_legend_cp2: "Point de controle 2",
        bezier_legend_control_lines: "Lignes de controle",
        // Animations
        anim_title: "Animations SVG",
        anim_subtitle: "Decouvrez les differentes techniques d'animation SVG",
        anim_css_title: "Animation CSS",
        anim_css_desc: "Les elements SVG peuvent etre animes avec les @keyframes CSS, comme n'importe quel element HTML.",
        anim_smil_title: "Animation SMIL",
        anim_smil_desc: "SMIL (Synchronized Multimedia Integration Language) permet d'animer directement dans le SVG avec des balises comme <animate>.",
        anim_stroke_title: "Animation de trait",
        anim_stroke_desc: "L'animation stroke-dashoffset permet de creer un effet de dessin progressif.",
        anim_morph_title: "Morphing de forme",
        anim_morph_desc: "En animant l'attribut 'd' d'un path, on peut transformer une forme en une autre.",
        anim_transform_title: "Transformations",
        anim_transform_desc: "Les transformations SVG (rotation, scale, translate) peuvent etre animees pour creer des effets dynamiques.",
        anim_interactive_title: "Animation interactive",
        anim_interactive_desc: "Combinez SVG et JavaScript pour creer des animations qui reagissent aux actions de l'utilisateur.",
        anim_interactive_click: "Cliquez ici !",
        anim_pulse_title: "Pulse",
        anim_pulse_desc: "Scale + transform-origin",
        anim_color_title: "Changement de couleur",
        anim_color_desc: "Transition de fill",
        anim_replay: "Rejouer",
        anim_animtransform_title: "<animateTransform>",
        anim_animtransform_desc: "Rotation native en SMIL",
        // Bezier
        bez_title: "Courbes de Bezier",
        bez_subtitle: "Explorez les courbes cubiques et quadratiques de maniere interactive",
        bez_quad_title: "Courbe quadratique (Q)",
        bez_quad_desc: "Definie par un point de depart, un point de controle et un point d'arrivee. La courbe est attiree vers le point de controle.",
        bez_cubic_title: "Courbe cubique (C)",
        bez_cubic_desc: "Definie par un point de depart, deux points de controle et un point d'arrivee. Offre plus de precision que la quadratique.",
        bez_drag: "Glissez les points de controle pour modifier la courbe !",
        bez_command: "Commande SVG :",
        bez_ai_title: "Une courbe ecrite par une IA",
        bez_ai_desc: `Voici la fleur en cloche d'une heather, dessinee par Claude. Toute la corolle est un seul <code>&lt;path&gt;</code> compose de <strong>commandes Q (quadratiques)</strong> chainees, exactement ce que tu as appris a manipuler plus haut.`,
        bez_ai_takeaway: `Chaque <code>Q</code> = un point de controle + un point d'arrivee. Sept commandes, une fleur. C'est ca qui rend les SVGs si interessants pour l'IA : <strong>sortie courte, structure claire, modifiable a la main</strong>. Tu pourrais ouvrir ce fichier et changer une couleur, deplacer un petale, ou ajouter une etamine, sans regenerer quoi que ce soit. Voir d'autres exemples dans la <a class="inline-link" href="gallery.html">galerie</a>.`,
        // Gallery
        gal_title: "Galerie SVG",
        gal_subtitle: "Une collection d'exemples SVG, des fleurs aux os en passant par l'IA",
        gal_tab_all: "Tout",
        gal_tab_flowers: "Fleurs",
        gal_tab_bones: "Os (etape par etape)",
        gal_tab_ai: "Genere par IA",
        gal_tab_cheatsheets: "Aide-memoires",
        gal_prompt: "Prompt :",
        gal_prompt_placeholder: "Le prompt sera ajoute prochainement",
        gal_techniques: `Les exemples ci-dessous combinent des techniques vues ailleurs dans le parcours : <a class="inline-link" href="svg-anatomy.html">anatomie</a> et formes de base, <a class="inline-link" href="bezier.html">courbes de Bezier</a> pour les paths, <a class="inline-link" href="animations.html">animations</a> pour le mouvement, et <a class="inline-link" href="live-demo.html">defs/use + variables CSS</a> pour les composants reutilisables comme l'os ci-dessous.`,
        gal_bone_techniques: `Chaque etape ajoute une technique : <a class="inline-link" href="svg-anatomy.html">viewBox</a>, transforms, gradients, filters. Le passage d'icone plate a os 3D illustre comment quelques attributs SVG bien choisis suffisent a creer de la profondeur.`,
        // Recipe (make-your-own SVG)
        recipe_title: "Recette : ton propre SVG parametrique",
        recipe_subtitle: "Le format que l'atelier comprend, en quelques lignes",
        recipe_principle_title: "Le principe",
        recipe_principle_desc: `Tu declares tes parametres en variables CSS dans une regle <code>:root</code>, placee dans une balise <code>&lt;style&gt;</code> en tout debut du SVG. Tu reutilises ces variables via <code>var(--ma-variable)</code> dans les attributs. C'est tout : le SVG reste 100% valide, ouvrable dans Inkscape, dans une page web, ou dans <a class="inline-link" href="workshop.html">l'atelier</a> qui detecte les variables et fabrique les controles automatiquement.`,
        recipe_inference_title: "Inference automatique",
        recipe_inference_desc: "Pas besoin d'annoter chaque variable. L'atelier devine le type a partir de la valeur :",
        recipe_th_value: "Valeur ressemble a",
        recipe_th_control: "Controle",
        recipe_ctrl_color: "Selecteur de couleur",
        recipe_ctrl_number: "Curseur numerique",
        recipe_ctrl_bool: "Case a cocher",
        recipe_ctrl_other_val: "N'importe quoi d'autre",
        recipe_ctrl_text: "Champ texte",
        recipe_hints_title: "Indices @ws (quand tu veux plus de controle)",
        recipe_hints_desc: `Ajoute un commentaire <code>/* @ws ... */</code> apres la valeur, sur la meme ligne, pour upgrader le controle. Les commentaires sont ignores par le navigateur, donc le SVG reste valide.`,
        recipe_th_hint: "Indice",
        recipe_th_what: "Effet",
        recipe_hint_number: "Curseur avec plage et pas explicites.",
        recipe_hint_select: "Menu deroulant avec les options listees.",
        recipe_hint_force: "Force le type de controle si l'inference se trompe.",
        recipe_hint_mix: `Marque la variable comme <strong>derivee</strong> d'une autre couleur. <code>amount</code> dans <code>[-1, 1]</code> : negatif assombrit, positif eclaircit. La variable suit automatiquement sa base.`,
        recipe_hint_seed: "Champ numerique avec un bouton random.",
        recipe_hint_ignore: "Ne genere aucun controle (utile pour les helpers internes).",
        recipe_example_title: "Exemple : deux couleurs liees",
        recipe_example_desc: `Le cas classique : une couleur principale et son ombre. Avec <code>@ws mix=...</code>, tu modifies une seule couleur et l'autre suit en temps reel.`,
        recipe_pitfalls_title: "Pieges a eviter",
        recipe_pitfall_root: `<strong>N'oublie pas <code>:root</code>.</strong> Les declarations doivent vivre dans une regle <code>:root { ... }</code>. Une variable declaree au top-level du stylesheet sans selecteur ne sera pas detectee.`,
        recipe_pitfall_style_position: `<strong>Place la balise <code>&lt;style&gt;</code> en premier enfant du <code>&lt;svg&gt;</code>.</strong> Pas dans un <code>&lt;g&gt;</code>, pas dans un <code>&lt;defs&gt;</code>. Premier enfant, c'est plus lisible et c'est ce que l'atelier cherche.`,
        recipe_pitfall_kebab: `<strong>Kebab-case pour les noms.</strong> <code>--light-x</code>, pas <code>--lightX</code>. Convention CSS, plus lisible.`,
        recipe_pitfall_hint_line: `<strong>L'indice <code>/* @ws ... */</code> doit etre sur la meme ligne</strong> que la declaration qu'il annote, apres le point-virgule. Sur une ligne separee, il ne sera pas associe.`,
        recipe_pitfall_no_amend: `<strong>Ne reecris pas le SVG quand tu changes une valeur dans l'atelier.</strong> Les modifications sont appliquees en surcouche via des styles inline ; le fichier source garde ses defauts.`,
        recipe_cta_title: "A toi de jouer",
        recipe_cta_desc: `Ouvre n'importe quel SVG de la <a class="inline-link" href="workshop.html">galerie de l'atelier</a> et clique sur <em>Voir le code source</em> pour voir le format en vrai. Puis copie-colle le template ci-dessus dans un fichier <code>.svg</code>, ajoute tes propres variables, et teste-le en glissant le fichier dans un navigateur.`,
        recipe_cta_btn: "Tester dans l'atelier",
        recipe_live_label: "Template minimal, modifie a gauche, regarde a droite",
        recipe_live_label2: "Edite le code, regarde le resultat",
        // Stories index
        stories_title: "Les histoires",
        stories_subtitle: "La presentation, racontee comme une serie d'actes",
        stories_intro: "Cette section est ce qui sert de fil rouge a la presentation. Chaque acte raconte un morceau de l'histoire, d'ou venait le besoin, comment l'IA a aide, ce qui a marche, ce qui a foire. Tu peux suivre dans l'ordre ou piocher.",
        stories_act1_title: "Acte 1 : D'ou ca vient",
        stories_act1_desc: "L'origine du projet : un chien, des chiots, et un besoin tres specifique d'images recoloriables avec du texte dedans.",
        stories_act2_title: "Acte 2 : Comment l'IA a aide",
        stories_act2_desc: "Les outils utilises (ChatGPT, les artifacts de Claude, Claude Code), leurs forces et leurs limites pour le SVG, les detours et les surprises.",
        // Story Part 1
        story_act_label: "Acte 1",
        story1_title: "Comment je me suis retrouve a coder un atelier de SVG",
        story1_subtitle: "Une histoire de chien, de site web et de variables CSS",
        story1_hello_title: "Qui suis-je",
        story1_hello_p1: "Simon Bedard, professeur d'informatique depuis 3 ans, Canadien en France depuis 10 ans, et grand curieux ayant fait aussi bien du jeu video que du design web dans mes temps libres. J'ai actuellement un interet tout particulier pour les outils augmentes par l'IA.",
        story1_hello_p2: "Aujourd'hui au menu : l'histoire de comment un projet personnel m'a force a reapprendre comment fonctionne le SVG.",
        story1_dog_title: `Une famille de cabots <span style="color: var(--text-light); font-weight: 400; font-size: 0.85em;">&rarr; 5 chiots plus tard</span>`,
        story1_dog_p1: `Mon chien Syn (Syntaxe pour les intimes) etait sur le point d'etre papa. Naturellement, j'ai voulu <a class="inline-link" href="https://javakhanstudio.github.io/SynAndKaya/" target="_blank" rel="noopener">faire un petit site pour presenter la petite famille</a> et celebrer l'occasion.`,
        story1_dog_p2: `<s style="color: var(--text-light);">J'ai donc facture une journee de travail a Syn.</s> C'etait le moment parfait pour faire un peu de veille techno, tester quelques outils et garder un souvenir de cet episode.`,
        story1_challenge_title: "Defi : un dogtag par chien",
        story1_challenge_p1: "Un de mes objectifs : afficher chaque chien avec sa propre medaille personnalisee. Onze chiens, onze medailles, toutes coherentes mais toutes uniques.",
        story1_challenge_p2: "Premier reflexe : demander a une IA de generer les images. Probleme :",
        story1_need_text: "Besoin d'une image <strong>avec du texte</strong>.",
        story1_need_color: "Besoin d'une image <strong>facilement recoloriable</strong>.",
        story1_need_size: "Besoin d'une <strong>taille flexible</strong>.",
        story1_need_draw: "Et surtout : <strong>je suis nul en dessin.</strong>",
        story1_examples_title: "La solution : un SVG",
        story1_examples_desc: "Apres plusieurs iterations, que nous verrons par la suite, la solution est rapidement devenue claire : utiliser un SVG. Meme template, trois chiens differents (le premier, c'est Syn, enfin, Syntaxe).",
        story1_tag_caption_syn: "Syn(taxe), le papa",
        story1_examples_note: "Le format est SVG : du texte XML, recolorable a la volee, redimensionnable a l'infini, et le nom du chien est juste... un attribut texte.",
        story1_play_title: "A toi de jouer",
        story1_play_desc: "Choisis un chien, change le nom, change la couleur de la medaille. Tout est genere en temps reel, c'est exactement le pattern qu'utilise le site SynAndKaya pour onze chiens differents.",
        story1_play_pick: "Choisis un chien :",
        story1_play_name: "Nom :",
        story1_play_color: "Couleur de la medaille :",
        story1_flip_label: "Luminance et seuil de flip :",
        story1_flip_lum: "Luminance :",
        story1_flip_border: "Bordure :",
        story1_flip_thresh: "Seuil :",
        story1_flip_explain: `<i class="fa-solid fa-code" style="color:#9b59b6; margin-right:0.4rem;"></i><strong>Et la bordure ?</strong> Elle n'est pas dans la palette : c'est du <strong>JavaScript</strong> qui la calcule a partir de la luminance perceptive de la couleur principale. Si <code>0.299&middot;R + 0.587&middot;G + 0.114&middot;B</code> (la luminance) passe sous le seuil, la bordure passe en <strong>blanc</strong> (sinon elle reste sombre). Glisse le seuil ou choisis Albert pour voir le flip se declencher.`,
        story1_ai_title: "Tout ca, possible grace a l'IA",
        story1_ai_p1: "Le travail ne fut pas simple, mais en une journee, accompagne par Claude, les tags etaient prets a l'emploi et uniques pour chaque chien.",
        story1_ai_p2: `Je suis nul en dessin, mais je sais ecrire un prompt et lire du code, les deux seuls skills necessaires pour creer une image vectorielle en 2026. C'est la-dessus qu'on va creuser dans la suite : <a class="inline-link" href="what-is-svg.html">pourquoi le SVG plait a l'IA</a>, comment <a class="inline-link" href="svg-anatomy.html">l'anatomie d'un fichier</a> se prete au format texte, et comment construire ses propres SVGs <a class="inline-link" href="make-svg.html">parametriques</a> avec un atelier interactif.`,
        story1_end_label: "Fin de l'acte 1",
        story1_end_p: "L'acte 2 raconte comment l'IA m'a aide a tout construire, les outils, les pieges, les surprises.",
        story1_end_back: "Retour aux histoires",
        story1_end_continue: "Continuer vers l'Acte 2 \u2192",
        // Story Part 2
        story_act2_label: "Acte 2",
        story2_title: "Comment l'IA a aide a tout construire",
        story2_subtitle: "Deux IA, deux outils, deux philosophies",
        story2_draft: "<strong>Note :</strong> cette page est un premier jet base sur les captures d'ecran fournies. Le texte definitif sera reecrit par Simon.",
        story2_gpt_title: "Premier essai : ChatGPT",
        story2_gpt_p1: "Premiere tentative : je decris mon besoin a ChatGPT. Le resultat qu'il me sort alors est techniquement un SVG qui compile et s'ouvre dans le navigateur. Je vous laisse cependant apprecier par vous-meme la qualite du produit.",
        story2_claude_title: "Deuxieme essai : Claude (artifacts)",
        story2_claude_p1: `Claude, via son systeme d'<strong>artifacts</strong>, fait quelque chose de different. Le SVG ne s'affiche pas juste en tant que code : il est rendu <strong>live</strong>, dans un panneau a droite, avec un vrai aperçu visuel. A chaque message qui modifie le SVG, le panneau se met a jour instantanement.`,
        story2_claude_p2: "La boucle d'iteration devient visuelle plutot que textuelle :",
        story2_claude_b1: `"Rends le metal plus sombre, plus pres de la couleur de la bordure", on voit le bone s'assombrir en temps reel.`,
        story2_claude_b2: `"Ajoute un effet grave au texte", un filtre SVG apparait, le texte prend un relief.`,
        story2_claude_b3: `"Un peu plus de contraste sur les bords", le highlight est ajuste en consequence.`,
        story2_claude_p3: `Pour du SVG specifiquement, ca change tout. La sortie finale (<code>boneV13.svg</code>, celui utilise dans <a class="inline-link" href="workshop.html">l'atelier</a>) est nettement plus riche : gradient lineaire multi-stops, pattern de texture diagonal, gradient de bord en overlay, filtre d'emboss sur le texte.`,
        story2_compare_title: "Les deux sorties, cote a cote",
        story2_compare_desc: "Memes coords, meme taille, aucune retouche, juste les fichiers SVG produits par chaque IA.",
        story2_evo_title: "L'evolution de l'os",
        story2_evo_desc: `Treize versions au total dans le repo. Voici cinq etapes choisies pour leur saut visuel, meme nom, meme palette, juste pour voir comment chaque iteration ajoute une couche.`,
        story2_evo_source_label: "SVG source, modifiable",
        story2_evo_tr_0: "Point de depart : un simple trace au stylo. Pas de fond, pas de texte, juste la silhouette pour valider la forme.",
        story2_evo_tr_1: `v1 -> v4 : le contour devient une vraie forme d'os, et un placeholder "Name of the dog" apparait. Premier signe que ca va devenir une medaille.`,
        story2_evo_tr_2: "v4 -> v5 : le contour devient solide, on remplit l'interieur d'un gradient metallique uniforme, le nom est rendu lisiblement par-dessus.",
        story2_evo_tr_3: "v5 -> v8 : un pattern de texture diagonal apparait dans le metal, et le nom prend un effet d'emboss SVG (filtre <feOffset>+<feGaussianBlur>+<feMerge>).",
        story2_evo_tr_4: "v8 -> v13 : polish final. Edge highlight via un gradient en overlay sur le bord, bordure plus contrastee, l'eclat plus credible. C'est cette version qui est utilisee dans l'atelier.",
        story2_evo_v1: "le contour brut",
        story2_evo_v4: "le placeholder du nom",
        story2_evo_v5: "premier rendu metallique",
        story2_evo_v8: "+ texture et emboss",
        story2_evo_v13: "la version finale",
        story2_evo_outro: `Entre v1 et v13 il y a beaucoup de retouches "live", du genre <em>"un peu plus de contraste sur les bords"</em>, <em>"le metal devrait etre plus sombre, plus pres de la bordure"</em>, <em>"le nom doit avoir l'air grave dans le metal"</em>. <small>(Les conversations exactes sont perdues, ces formulations sont des reconstitutions a partir des changements visibles entre versions.)</small> C'est exactement ce genre d'iteration que l'artifact panel rend possible : une boucle voir-corriger en quelques secondes.`,
        story2_gpt_raw_title: "Sauf que finalement...",
        story2_gpt_raw_caption: "Output ChatGPT, taille reelle, palette par defaut.",
        story2_gpt_raw_p: "Apres plusieurs retouches, le resultat final s'approche lentement de ce que j'avais en tete, mais j'en ai deja marre, et je decide d'aller voir ailleurs si j'y suis.",
        story2_anat_title: "Anatomie d'un dogtag",
        story2_anat_desc: "Le dogtag complet, puis on zoom sur chaque technique qui le compose.",
        story2_anat_toggle: "Afficher les reperes",
        story2_anat_zoom_title: "Quatre techniques, en zoom",
        story2_card_grad_title: "Le gradient metallique",
        story2_card_edge_title: "L'edge highlight (2 paths)",
        story2_card_tex_title: "Le pattern de texture",
        story2_card_emboss_title: "Le filtre emboss (texte grave)",
        story2_card_reflet: "Reflet :",
        story2_card_ombre: "Ombre :",
        story2_card_metal: "Couleur du metal :",
        story2_card_fond: "Fond :",
        story2_card_diagonales: "Diagonales :",
        story2_card_reset: "Reinitialiser",
        story2_zoom_grad: `Un <code>linearGradient</code> diagonal avec <strong>8 stops</strong> au lieu des 2-3 habituels. La sequence va du sombre au clair, repique au mid, redescend, puis termine sur le tres clair. C'est cette alternance qui donne l'illusion du metal poli, les yeux interpretent ces variations comme des reflets.`,
        story2_zoom_edge: `L'os est dessine <strong>deux fois</strong> sur le meme path. La premiere copie a le gradient metallique en fill et la bordure sombre. La deuxieme, par-dessus, n'a <em>aucun</em> fill, juste un <code>stroke</code> peint avec un gradient blanc-vers-transparent. C'est ce double-passage qui simule un reflet de lumiere sur le bord superieur de l'os.`,
        story2_zoom_pattern: `Un <code>pattern</code> minuscule (2&times;5 unites, repete sans fin) avec deux croix diagonales tres tenues. Vu de loin, ca donne l'effet "metal brosse" sans alourdir le fichier, un seul element <code>&lt;pattern&gt;</code> remplace des milliers de petits paths.`,
        story2_zoom_emboss: `L'effet "grave dans le metal" est une chaine de filtres SVG : <code>feOffset</code> decale une copie de l'alpha du texte, <code>feGaussianBlur</code> la flou, <code>feFlood</code> + <code>feComposite</code> la teinte en noir semi-transparent, et <code>feMerge</code> empile l'ombre <em>derriere</em> le texte original. Resultat : du relief sans avoir a redessiner le texte.`,
        story2_anat_outro: `Combine ces quatre techniques + un cercle stroke pour la photo + un calcul JS pour la couleur de bordure (le <a class="inline-link" href="story-part1.html">flip de luminance vu a l'acte 1</a>), et tu as un dogtag complet. C'est ca qu'on reconstruit pour chacun des onze chiens, il suffit de changer le nom, la photo et la couleur de base.`,
        story2_compare_gpt_meta: "1 path, 1 radial gradient, 3 color stops, 1 stroke. Propre mais plat.",
        story2_compare_claude_meta: "Gradient multi-stops, pattern diagonal de texture, gradient d'edge highlight, filtre d'emboss pour le texte. Plus riche.",
        story2_table_axis: "Critere",
        story2_table_preview: "Apercu live",
        story2_table_yes: "Oui (artifact)",
        story2_table_no: "Non",
        story2_table_iter: "Iteration visuelle",
        story2_table_iter_gpt: "Texte uniquement",
        story2_table_iter_claude: "On voit le changement a chaque message",
        story2_table_complex: "Complexite du SVG sortant",
        story2_table_complex_gpt: "Simple, efficace",
        story2_table_complex_claude: "Plus riche par defaut",
        story2_table_edit: "Editer un fichier existant",
        story2_table_edit_gpt: "Via copier-coller",
        story2_table_edit_claude: "Via copier-coller (l'interface web)",
        story2_js_title: "SVG + JavaScript = combo",
        story2_js_p1: "Une fois que ton SVG est texte, tu peux le manipuler avec n'importe quel langage. Avec un peu de JavaScript, tu peux ajouter, dupliquer, animer ou recolorer des elements en temps reel, sans jamais regenerer le fichier.",
        story2_js_p2: "Demonstration : un bouton qui ajoute un dogtag avec un nom et une couleur tires au hasard. C'est une dizaine de lignes de JS qui clonent le template, changent le texte et la palette, et l'inserent dans la page.",
        story2_js_btn: "+ Ajouter un dogtag",
        story2_js_reset: "Reinitialiser",
        story2_js_p3: `L'IA est exceptionnellement bonne pour cabler ces deux mondes. Decrire en francais "<em>un bouton qui ajoute une nouvelle medaille avec un nom au hasard</em>", et obtenir simultanement le bon SVG, le bon JavaScript, et le bon CSS, c'est ce qui fait passer une page statique a un outil vivant.`,
        story2_lesson_title: "La lecon",
        story2_lesson_p1: `Bon. Soyons honnetes : <strong>GPT fut lamentable</strong> pour ce besoin precis. (C'est aussi assez drole de voir une IA d'une compagnie en competition essayer de defendre une autre, donc rectifions le tir.)`,
        story2_lesson_p2: `Ce qu'il faut comprendre, c'est que <strong>les bons outils permettent les bons resultats</strong>. Le format texte du SVG permet de comprendre rapidement une image et de l'affecter directement avec des variables, exactement comme on le ferait avec du code. Combine avec un outil qui rend ce code en direct (artifacts) ou qui edite tes fichiers a ta place (Claude Code), et tu passes de "generateur d'image" a "atelier".`,
        story2_lesson_p3: "Le vrai gain, finalement, ce n'est pas le code genere en lui-meme, c'est la boucle d'iteration.",
        story2_end_label: "Fin de l'acte 2",
        story2_end_continue: "Continuer vers l'Acte 3 \u2192",
        // Gallery captions
        gallery_bone_v1: "Icone de base (16x16)",
        gallery_bone_v2: "+ rotation (transform)",
        gallery_bone_v3: "+ matrix transform + texte",
        gallery_bone_v4: "+ viewBox + layout",
        gallery_bone_v5: "+ gradients + filtres",
        gallery_bone_v6: "+ gradient de reflet",
        gallery_bone_v7: "+ ajustements",
        gallery_bone_v8: "+ ombre et profondeur",
        gallery_bone_v9: "+ pattern de texture",
        gallery_bone_v10: "+ effets de bord",
        gallery_bone_v11: "+ filtre emboss pour le texte",
        gallery_bone_v12: "+ finitions",
        gallery_bone_v13: "Final : os metallique complet",
        gallery_blackthorn_desc: "Prunellier, variables CSS, pattern defs/use",
        gallery_blackthornv2_desc: "Variation avec petales raffines",
        gallery_rose_desc: "Superposition de petales avec gradients",
        gallery_daisy_desc: "Arrangement symetrique des petales",
        gallery_bluebell_desc: "Fleur en cloche avec courbes",
        gallery_pansy_desc: "Petales multicolores detailles",
        gallery_wildrose_desc: "Design progressif d'eglantine",
        gallery_vine_desc: "Trace courbe avec couches de profondeur",
        gallery_ai_claude: "IA : Claude",
        gallery_ai_deepseek: "IA : DeepSeek",
        gallery_ai_gpt: "IA : ChatGPT",
        gallery_ai_gpt_bone: "IA : ChatGPT, variante dogtag",
        gallery_tool_cheat: "Formes, paths, styling, transforms, filtres",
        gallery_tool_bezier: "Reference beziers quadratiques et cubiques",
        gallery_tool_rotation: "Demonstrations de rotation et transform",
        gallery_tool_3dtext: "Gradients avances pour le rendu 3D de texte",
        gallery_tool_patte: "Element decoratif simple et reutilisable",
        // Act 3 — story-part3.html
        story3_label: "Acte 3",
        story3_hero_title: "Creation SVG complete",
        story3_hero_subtitle: "Ce que l'IA ne fait pas (encore) toute seule",
        story3_concept_title: "Une carte a deux faces",
        story3_concept_p1: "Autre projet, autre jour. Je voulais permettre aux gens de tirer une carte de tarot. Probleme : selectionner directement une image generee par IA me semblait trop lache. Une carte, c'est deux faces.",
        story3_concept_p2: "Logique : le devant montrerait l'arcane (AI-generated), et la carte se retournerait au clic grace a un composant CSS 3D. Mais que mettre au dos ? Encore une image IA ? Non, je voulais quelque chose de personnel, un SVG qui puisse evoluer avec les choix de l'utilisateur.",
        story3_concept_p3: "L'IA est excellente pour imaginer une face avant. Pour le dos je voulais coder un langage visuel coherent, reutilisable, parametrable. Bienvenue dans un SVG de 451 lignes.",
        story3_card_title: "La carte",
        story3_card_desc: `Joue avec les couleurs et les themes. Chaque theme redessine les quatre coins avec un autre set d'ornements : <strong>Chair</strong> (organique), <strong>Matiere</strong> (geometrique) ou <strong>Ame</strong> (mystique).`,
        story3_card_color_bg: "Fond :",
        story3_card_color_pyramid: "Pyramide :",
        story3_card_color_eye: "Oeil :",
        story3_card_color_edge: "Contour :",
        story3_card_theme: "Theme :",
        story3_card_theme_flesh: "Chair",
        story3_card_theme_matter: "Matiere",
        story3_card_theme_soul: "Ame",
        story3_card_reset: "Reinitialiser",
        story3_anat_title: "Anatomie de la carte",
        story3_anat_desc: "Six techniques SVG qui composent la carte. Chacune s'utilise independamment et se combine avec les autres, c'est ce qui fait la richesse du format.",
        story3_card1_title: "Variables CSS",
        story3_card1_desc: `Un seul <code>:root { }</code> dans le SVG expose cinq couleurs. Tout ce qui reference <code>var(--couleur)</code> se met a jour en temps reel, sans regenerer le fichier.`,
        story3_card2_title: "&lt;defs&gt; et &lt;use&gt;",
        story3_card2_desc: `Une forme est definie une fois dans <code>&lt;defs&gt;</code> puis instanciee avec <code>&lt;use href="#id"&gt;</code> avec un transform different. La meme brique, rayon ou triangle est reutilise des dizaines de fois sans gonfler le fichier.`,
        story3_card3_title: "Gradients",
        story3_card3_desc: "Quatre gradients superposes (radiaux pour l'iris et la sclere, lineaires pour les ornements) construisent la profondeur. L'iris seul combine 3 stops avec opacites variables.",
        story3_card4_title: "Filtres animes",
        story3_card4_desc: `Les chaines <code>feGaussianBlur</code> + <code>feMerge</code> donnent le halo. L'element <code>&lt;animate&gt;</code> de SMIL fait pulser la valeur <code>stdDeviation</code> entre 2 et 7 sur 3 secondes, en boucle.`,
        story3_card5_title: "Clip paths",
        story3_card5_desc: `La pyramide est un triangle, rempli de briques rectangulaires. Un <code>&lt;clipPath&gt;</code> au contour triangulaire decoupe les briques qui depassent : on dessine un rectangle bete, le clip fait le reste.`,
        story3_card6_title: "Symetrie via transform",
        story3_card6_desc: `L'ornement d'un coin est dessine une fois, puis duplique aux trois autres avec <code>scale(-1,1)</code>, <code>scale(1,-1)</code>, <code>scale(-1,-1)</code>. Change un coin, tous les autres suivent.`,
        story3_animated_title: "Et si on l'animait ?",
        story3_animated_desc: "Meme carte, mais avec quelques animations CSS : une rotation lente sur le motif de rayons, une derive de teinte sur la palette, une levitation discrete. Le SVG, c'est du texte qui peut tout faire.",
        story3_license: "\u00a9 Simon Bedard. SVG partage a des fins educatives. Usage commercial interdit.",
        story3_end_label: "Fin de l'acte 3",
        story3_end_p: "Voila. Trois actes, un fil rouge : l'IA aide a construire, mais les decisions de design restent humaines.",
        story3_end_continue: "Aller a l'atelier \u2192",
        // Stories index entry for Act 3
        stories_act3_title: "Acte 3 : Creation SVG complete",
        stories_act3_desc: "Quand l'IA seule ne suffit pas : anatomie d'un SVG ecrit a la main de 451 lignes, variables, defs/use, filtres animes, clip paths, symetrie.",
    },
    en: {
        nav_home: "Home",
        nav_stories: "Stories",
        nav_concepts: "Concepts",
        nav_what: "What is it?",
        nav_anatomy: "Anatomy",
        nav_live: "Live Editing",
        nav_animations: "Animations",
        nav_bezier: "Bezier Curves",
        nav_gallery: "Gallery",
        nav_workshop: "Workshop",
        nav_recipe: "Recipe",
        workshop_title: "SVG Workshop",
        workshop_subtitle: "Pick an illustration and tweak its CSS variables in real time",
        workshop_how_title: "How it works",
        workshop_how_desc: "Each gallery SVG declares its parameters in a <code>:root</code> rule and tacks on a <code>/* @ws ... */</code> comment that tells the workshop which control to build. That's it. The file stays a valid SVG you can open in any browser.",
        workshop_how_extra: "<strong>Compare</strong> places the SVG and the source photo side-by-side, <strong>Download</strong> grabs your SVG with your edits, and <strong>View source</strong> below the illustration opens the raw file in a new tab.",
        workshop_view_source: "View source \u2192",
        workshop_controls: "Controls",
        workshop_reset: "Reset",
        workshop_empty: "This SVG does not expose any variables.",
        workshop_view_svg: "SVG",
        workshop_view_compare: "Compare",
        workshop_view_photo: "Photo",
        workshop_download: "Download",
        workshop_editor_title: "Want to go further?",
        workshop_editor_desc: "This page is a static showcase. For the full workshop \u2014 file watching, snapshots, reference-photo import, similarity metrics \u2014 clone the repo and start the local server:",
        workshop_editor_link: "Open the interactive editor \u2192",
        footer_made: "Made by",
        home_title: "SVG Workshop",
        home_subtitle: "Discover the power of SVG for the web",
        home_pitch_title: "SVG, an underrated tool",
        home_pitch: `SVG is an invaluable tool for any web developer. <a class="inline-link" href="what-is-svg.html">Optimized for all screen sizes</a>, it offers pixel-perfect power and elegance. But that's not all: with <a class="inline-link" href="live-demo.html">unmatched flexibility</a>, it can adapt to your users with <a class="inline-link" href="animations.html">minimal JavaScript</a>.`,
        home_problem_title: "The only problem...",
        home_problem: `Its complexity can be intimidating (have a look at <a class="inline-link" href="svg-anatomy.html">the anatomy of a path</a> or <a class="inline-link" href="bezier.html">Bezier curves</a>):`,
        home_solution: `This sequence may seem abstract to a human, but fortunately, not to an AI, explore <a class="inline-link" href="workshop.html">the workshop</a> or <a class="inline-link" href="gallery.html">the gallery</a>!`,
        home_cta: "Come discover or rediscover this image format, in a short presentation with multiple examples, some generated live!",
        home_start: "Start exploring",
        home_concepts_pitch: "Want a bird's-eye view before diving in? Take a look at the concepts map.",
        home_concepts_cta: "See the concepts map",
        concepts_title: "Concepts map",
        concepts_subtitle: "A bird's-eye view of the journey, chapter by chapter",
        concepts_explore: "Explore",
        concepts_intro: "Each card leads to the page that goes deeper. Walk it in order, or jump to whatever sparks your curiosity.",
        concepts_what_desc: "Vector vs raster, and why it changes everything at zoom.",
        concepts_anatomy_desc: "ViewBox, primitive shapes, the <path> element, styling.",
        concepts_live_desc: "Tweak fill, stroke, rotation and watch the code update.",
        concepts_anim_desc: "CSS keyframes, SMIL, stroke-dashoffset, path morphing.",
        concepts_bezier_desc: "Quadratics, cubics, draggable control points.",
        concepts_workshop_desc: "Parametric SVGs with live controls (colors, sizes, modes).",
        concepts_gallery_desc: "Examples: flowers, step-by-step bones, AI generations, cheat sheets.",
        concepts_recipe_desc: "The @ws format for making your own parametric SVGs that work in the workshop.",
        concepts_cta_recipe: "Cook \u2192",
        concepts_cta_what: "Discover \u2192",
        concepts_cta_anatomy: "Take apart \u2192",
        concepts_cta_live: "Try it \u2192",
        concepts_cta_anim: "Animate \u2192",
        concepts_cta_bezier: "Bend it \u2192",
        concepts_cta_workshop: "Tinker \u2192",
        concepts_cta_gallery: "Browse \u2192",
        what_title: "What is an SVG?",
        what_subtitle: "Understanding the difference between vector and raster images",
        what_vector_title: "Vector Image (SVG)",
        what_raster_title: "Raster Image (PNG/JPG)",
        what_zoom: "Zoom in to see the difference!",
        what_vector_desc: "Defined by mathematical formulas. Each shape is described by equations, allowing infinite resizing without quality loss.",
        what_raster_desc: "Composed of a grid of pixels. Each pixel has a fixed color. When zooming, pixels become visible and the image appears blurry.",
        what_advantages_title: "SVG Advantages",
        what_adv1: "Infinitely scalable without quality loss",
        what_adv2: "Lightweight files for simple shapes",
        what_adv3: "Modifiable via CSS and JavaScript",
        what_adv4: "Natively animatable",
        what_adv5: "Accessible (text indexable by search engines)",
        what_adv6: "Ideal for icons, logos, illustrations",
        what_when_title: "When to use SVG?",
        what_when_svg: "SVG: icons, logos, illustrations, charts, animations",
        what_when_raster: "PNG/JPG: photos, complex images with many colors",
        what_ai_title: "Why AI loves SVG",
        what_ai_p1: "An SVG is just text. Readable, structured XML with self-explanatory attribute names (cx, fill, d...). For a large language model, that's exactly its home turf: it manipulates tokens, not pixels.",
        what_ai_p2: `The same image as PNG would be an opaque grid of pixels. An AI can <em>recognize</em> what it sees, but it can't precisely modify it. With SVG, it can add a shape, change a color, adjust a <a class="inline-link" href="bezier.html">curve</a>, or even generate the whole image from a description.`,
        what_ai_p3: `Every AI illustration in the <a class="inline-link" href="gallery.html">gallery</a> was produced this way: a prompt, a text SVG response, ready to drop into the browser.`,
        anat_title: "Anatomy of an SVG",
        anat_subtitle: "Understanding SVG code structure",
        anat_structure_title: "Basic structure",
        anat_structure_desc: "An SVG is an XML document with a root <svg> element and child elements that describe shapes.",
        anat_viewbox_title: "The ViewBox",
        anat_viewbox_desc: "The viewBox attribute defines the SVG's internal coordinate system. It enables responsive graphics that adapt to any size.",
        anat_shapes_title: "Basic shapes",
        anat_shapes_desc: "SVG provides several primitive shapes to build your graphics.",
        anat_path_title: "The Path element",
        anat_path_desc: "The <path> element is the most powerful in SVG. It can draw any shape using movement commands.",
        anat_path_commands: `Main commands: M (move), L (line), H (horizontal), V (vertical), <a class="inline-link" href="bezier.html">C (cubic curve), Q (quadratic curve)</a>, A (arc), Z (close)`,
        anat_path_ai: `<i class="fa-solid fa-robot" style="color:#9b59b6; margin-right:0.4rem;"></i><strong>AI angle:</strong> these commands (<code>M</code>, <code>C</code>, <code>Q</code>, <code>L</code>...) are exactly what an LLM types when you ask it to draw. A flower, a heart, a logo: each becomes a string like <code>d="M30,45 C30,45 10,30 10,18..."</code>. To dive deeper, see <a class="inline-link" href="bezier.html">Bezier curves</a>.`,
        anat_styling_title: "Styling",
        anat_styling_desc: `SVG elements can be styled with attributes, inline CSS, or external stylesheets. Combined with <strong>CSS variables</strong>, the same SVG becomes parametric on the fly, which is exactly what <a class="inline-link" href="workshop.html">the workshop</a> does.`,
        anat_cheatsheet: "Complete cheat sheet",
        live_title: "Live Editing",
        live_subtitle: "Modify SVG attributes and see the result instantly",
        live_shape_title: "Interactive Shape",
        live_shape_desc: "Use the controls below to modify this SVG shape's properties in real time.",
        live_code_title: "Generated Code",
        live_code_desc: "The SVG code updates automatically as you change the controls.",
        live_fill: "Fill",
        live_stroke: "Stroke",
        live_strokew: "Width",
        live_opacity: "Opacity",
        live_rotation: "Rotation",
        live_scale: "Scale",
        live_radius: "Radius",
        live_sides: "Sides",
        live_shape: "Shape",
        live_circle: "Circle",
        live_rect: "Rectangle",
        live_polygon: "Polygon",
        live_star: "Star",
        live_reuse_desc: `An SVG can define reusable elements with <code>&lt;defs&gt;</code> and <code>&lt;use&gt;</code>. Combine that with CSS variables to build customizable components.`,
        live_reuse_ai: `<i class="fa-solid fa-robot" style="color:#9b59b6; margin-right:0.4rem;"></i><strong>The AI app pattern:</strong> what you see here is exactly the recipe behind any AI-augmented app: an SVG <em>template</em> (the bone, its shape) plus <em>parameters</em> (colors, text) that can come from a human... or from an LLM. <a class="inline-link" href="workshop.html">The workshop</a> takes the idea further with a full gallery of parametric SVGs.`,
        live_dog_name: "Dog name",
        live_color_dark: "Dark color",
        live_color_light: "Light color",
        live_text_color: "Text color",
        bezier_legend_start_end: "Start / End",
        bezier_legend_control_point: "Control point",
        bezier_legend_curve: "Curve",
        bezier_legend_cp1: "Control point 1",
        bezier_legend_cp2: "Control point 2",
        bezier_legend_control_lines: "Control lines",
        anim_title: "SVG Animations",
        anim_subtitle: "Discover the different SVG animation techniques",
        anim_css_title: "CSS Animation",
        anim_css_desc: "SVG elements can be animated with CSS @keyframes, just like any HTML element.",
        anim_smil_title: "SMIL Animation",
        anim_smil_desc: "SMIL (Synchronized Multimedia Integration Language) lets you animate directly within SVG using tags like <animate>.",
        anim_stroke_title: "Stroke Animation",
        anim_stroke_desc: "The stroke-dashoffset animation creates a progressive drawing effect.",
        anim_morph_title: "Shape Morphing",
        anim_morph_desc: "By animating a path's 'd' attribute, you can transform one shape into another.",
        anim_transform_title: "Transformations",
        anim_transform_desc: "SVG transforms (rotation, scale, translate) can be animated for dynamic effects.",
        anim_interactive_title: "Interactive Animation",
        anim_interactive_desc: "Combine SVG and JavaScript to create animations that react to user actions.",
        anim_interactive_click: "Click / Tap me!",
        anim_pulse_title: "Pulse",
        anim_pulse_desc: "Scale + transform-origin",
        anim_color_title: "Color shift",
        anim_color_desc: "fill transition",
        anim_replay: "Replay",
        anim_animtransform_title: "<animateTransform>",
        anim_animtransform_desc: "Native SMIL rotation",
        bez_title: "Bezier Curves",
        bez_subtitle: "Explore cubic and quadratic curves interactively",
        bez_quad_title: "Quadratic curve (Q)",
        bez_quad_desc: "Defined by a start point, a control point and an end point. The curve is pulled toward the control point.",
        bez_cubic_title: "Cubic curve (C)",
        bez_cubic_desc: "Defined by a start point, two control points and an end point. Offers more precision than quadratic.",
        bez_drag: "Drag the control points to modify the curve!",
        bez_command: "SVG command:",
        bez_ai_title: "A curve written by an AI",
        bez_ai_desc: `Here's a heather's bell-shaped flower, drawn by Claude. The whole corolla is a single <code>&lt;path&gt;</code> made of chained <strong>Q (quadratic) commands</strong>exactly what you just learned to manipulate above.`,
        bez_ai_takeaway: `Each <code>Q</code> = one control point + one endpoint. Seven commands, one flower. That's what makes SVG so interesting for AI: <strong>short output, clear structure, hand-editable</strong>. You could open this file and change a color, move a petal, or add a stamen, without regenerating anything. More examples in the <a class="inline-link" href="gallery.html">gallery</a>.`,
        gal_title: "SVG Gallery",
        gal_subtitle: "A collection of SVG examples, from flowers to bones to AI-generated art",
        gal_tab_all: "All",
        gal_tab_flowers: "Flowers",
        gal_tab_bones: "Bones (step by step)",
        gal_tab_ai: "AI Generated",
        gal_tab_cheatsheets: "Cheat Sheets",
        gal_prompt: "Prompt:",
        gal_prompt_placeholder: "Prompt coming soon",
        gal_techniques: `The examples below combine techniques you've seen elsewhere on the journey: <a class="inline-link" href="svg-anatomy.html">anatomy</a> and basic shapes, <a class="inline-link" href="bezier.html">Bezier curves</a> for paths, <a class="inline-link" href="animations.html">animations</a> for motion, and <a class="inline-link" href="live-demo.html">defs/use + CSS variables</a> for reusable components like the bone below.`,
        gal_bone_techniques: `Each step adds a technique: <a class="inline-link" href="svg-anatomy.html">viewBox</a>, transforms, gradients, filters. The shift from flat icon to 3D bone shows how a few well-chosen SVG attributes are enough to build depth.`,
        recipe_title: "Recipe: your own parametric SVG",
        recipe_subtitle: "The format the workshop reads, in a few lines",
        recipe_principle_title: "The principle",
        recipe_principle_desc: `Declare your parameters as CSS variables in a <code>:root</code> rule, inside a <code>&lt;style&gt;</code> tag at the very top of the SVG. Reference them via <code>var(--my-variable)</code> in attributes. That's it: the SVG stays 100% valid, openable in Inkscape, in a web page, or in <a class="inline-link" href="workshop.html">the workshop</a> which detects the variables and builds the controls automatically.`,
        recipe_inference_title: "Automatic inference",
        recipe_inference_desc: "No need to annotate every variable. The workshop guesses the type from the value:",
        recipe_th_value: "Value looks like",
        recipe_th_control: "Control",
        recipe_ctrl_color: "Color picker",
        recipe_ctrl_number: "Number slider",
        recipe_ctrl_bool: "Checkbox",
        recipe_ctrl_other_val: "Anything else",
        recipe_ctrl_text: "Text input",
        recipe_hints_title: "@ws hints (when you want more control)",
        recipe_hints_desc: `Add a <code>/* @ws ... */</code> comment after the value, on the same line, to upgrade the control. Comments are ignored by the browser, so the SVG stays valid.`,
        recipe_th_hint: "Hint",
        recipe_th_what: "Effect",
        recipe_hint_number: "Slider with explicit range and step.",
        recipe_hint_select: "Dropdown with the listed options.",
        recipe_hint_force: "Forces the control type when inference picks the wrong one.",
        recipe_hint_mix: `Marks the variable as <strong>derived</strong> from another color. <code>amount</code> in <code>[-1, 1]</code>: negative darkens, positive lightens. The variable follows its base automatically.`,
        recipe_hint_seed: "Number input with a randomize button.",
        recipe_hint_ignore: "Skips control generation (useful for internal helpers).",
        recipe_example_title: "Example: two linked colors",
        recipe_example_desc: `The classic case: a primary color and its shadow. With <code>@ws mix=...</code>, you tweak one and the other follows in real time.`,
        recipe_pitfalls_title: "Common pitfalls",
        recipe_pitfall_root: `<strong>Don't forget <code>:root</code>.</strong> Declarations must live inside a <code>:root { ... }</code> rule. Variables declared at the stylesheet's top level without a selector won't be detected.`,
        recipe_pitfall_style_position: `<strong>Place the <code>&lt;style&gt;</code> tag as the first child of <code>&lt;svg&gt;</code>.</strong> Not inside a <code>&lt;g&gt;</code>, not inside a <code>&lt;defs&gt;</code>. First child, clearer, and it's what the workshop expects.`,
        recipe_pitfall_kebab: `<strong>Kebab-case for names.</strong> <code>--light-x</code>, not <code>--lightX</code>. CSS convention, plays nicely.`,
        recipe_pitfall_hint_line: `<strong>The <code>/* @ws ... */</code> hint must be on the same line</strong> as the declaration it annotates, after the semicolon. On a separate line, it won't be associated.`,
        recipe_pitfall_no_amend: `<strong>Don't rewrite the SVG when you change a value in the workshop.</strong> Edits are applied as inline-style overrides on top; the source file keeps its defaults.`,
        recipe_cta_title: "Your turn",
        recipe_cta_desc: `Open any SVG in the <a class="inline-link" href="workshop.html">workshop gallery</a> and click <em>View source</em> to see the format for real. Then copy-paste the template above into a <code>.svg</code> file, add your own variables, and test it by dragging the file into a browser.`,
        recipe_cta_btn: "Try it in the workshop",
        recipe_live_label: "Minimal template, edit on the left, watch on the right",
        recipe_live_label2: "Edit the code, watch the result",
        // Stories index
        stories_title: "The stories",
        stories_subtitle: "The talk, told as a series of acts",
        stories_intro: "This section is the through-line of the talk. Each act tells a piece of the story, where the need came from, how AI helped, what worked, what didn't. Walk it in order, or pick.",
        stories_act1_title: "Act 1 : Where it came from",
        stories_act1_desc: "Origin of the project: a dog, puppies, and a very specific need for recolorable images with text inside them.",
        stories_act2_title: "Act 2 : How AI helped",
        stories_act2_desc: "The tools used (ChatGPT, Claude artifacts, Claude Code), their strengths and limits for SVG, the detours and the surprises.",
        // Story Part 1
        story_act_label: "Act 1",
        story1_title: "How I ended up coding a parametric-SVG workshop",
        story1_subtitle: "A story about a dog, a website, and CSS variables",
        story1_hello_title: "Who I am",
        story1_hello_p1: "Simon Bedard, computer-science teacher for 3 years, Canadian living in France for 10, and a generalist who's dabbled in game dev as much as in web design. Right now my main interest is AI-augmented tooling.",
        story1_hello_p2: "Today's menu: how a personal project forced me to relearn how SVG actually works.",
        story1_dog_title: `A family of mutts <span style="color: var(--text-light); font-weight: 400; font-size: 0.85em;">&rarr; 5 puppies later</span>`,
        story1_dog_p1: `My dog Syn (Syntaxe to his friends) was about to be a dad. Naturally, I wanted to <a class="inline-link" href="https://javakhanstudio.github.io/SynAndKaya/" target="_blank" rel="noopener">build a little site to introduce the family</a> and mark the occasion.`,
        story1_dog_p2: `<s style="color: var(--text-light);">I billed Syn one day of dev work for the gig.</s> It was the perfect excuse to scout some new tools, try a few things, and keep a memory of that period.`,
        story1_challenge_title: "Challenge: a dog tag per dog",
        story1_challenge_p1: "One of my goals: show every dog with its own personalized tag. Eleven dogs, eleven tags, all consistent but all unique.",
        story1_challenge_p2: "First instinct: ask an AI to generate the images. The problem:",
        story1_need_text: "Need an image <strong>with text in it</strong>.",
        story1_need_color: "Need an image <strong>easily recolorable</strong>.",
        story1_need_size: "Need a <strong>flexible size</strong>.",
        story1_need_draw: "And above all: <strong>I'm useless at drawing.</strong>",
        story1_examples_title: "The solution: an SVG",
        story1_examples_desc: "After several iterations, which we'll see in a bit, the solution became obvious: use an SVG. Same template, three different dogs (the first one is Syn, well, Syntaxe).",
        story1_tag_caption_syn: "Syn(taxe), the dad",
        story1_examples_note: "The format is SVG: text-based XML, recolorable on the fly, infinitely scalable, and the dog's name is just... a text attribute.",
        story1_play_title: "Your turn",
        story1_play_desc: "Pick a dog, change the name, change the tag color. Everything renders in real time, that's exactly the pattern the SynAndKaya site uses for eleven different dogs.",
        story1_play_pick: "Pick a dog:",
        story1_play_name: "Name:",
        story1_play_color: "Tag color:",
        story1_flip_label: "Luminance and flip threshold:",
        story1_flip_lum: "Luminance:",
        story1_flip_border: "Border:",
        story1_flip_thresh: "Threshold:",
        story1_flip_explain: `<i class="fa-solid fa-code" style="color:#9b59b6; margin-right:0.4rem;"></i><strong>What about the border?</strong> It's not in the palette, it's <strong>JavaScript</strong> that computes it from the perceptual luminance of the main color. If <code>0.299&middot;R + 0.587&middot;G + 0.114&middot;B</code> (the luminance) drops below the threshold, the border flips to <strong>white</strong> (otherwise it stays dark). Drag the threshold or pick Albert to see the flip kick in.`,
        story1_ai_title: "All this, made possible by AI",
        story1_ai_p1: "It wasn't easy, but in a single day, with Claude alongside, the tags were ready to ship and unique to each dog.",
        story1_ai_p2: `I'm useless at drawing, but I can write a prompt and read code, the only two skills you need to make a vector image in 2026. That's what we'll dig into next: <a class="inline-link" href="what-is-svg.html">why AI loves SVG</a>, how <a class="inline-link" href="svg-anatomy.html">a file's anatomy</a> lends itself to text, and how to build your own <a class="inline-link" href="make-svg.html">parametric SVGs</a> with an interactive workshop.`,
        story1_end_label: "End of Act 1",
        story1_end_p: "Act 2 covers how AI helped me build the whole thing, the tools, the pitfalls, the surprises.",
        story1_end_back: "Back to the stories",
        story1_end_continue: "Continue to Act 2 \u2192",
        // Story Part 2
        story_act2_label: "Act 2",
        story2_title: "How AI helped build the whole thing",
        story2_subtitle: "Two AIs, two tools, two philosophies",
        story2_draft: "<strong>Note:</strong> this page is a first draft based on the provided screenshots. The final copy will be rewritten by Simon.",
        story2_gpt_title: "First try: ChatGPT",
        story2_gpt_p1: "First attempt: I describe the need to ChatGPT. The output is technically valid SVG, it compiles, it opens in the browser. But I'll let you appreciate the quality of the product for yourself.",
        story2_claude_title: "Second try: Claude (artifacts)",
        story2_claude_p1: `Claude, via its <strong>artifacts</strong> system, does something different. The SVG isn't just shown as code, it's rendered <strong>live</strong>, in a panel on the right, with a real visual preview. Every message that modifies the SVG updates the panel instantly.`,
        story2_claude_p2: "The iteration loop becomes visual rather than textual:",
        story2_claude_b1: `"Make the metal darker, closer to the border color", and you watch the bone darken in real time.`,
        story2_claude_b2: `"Add an engraved effect to the text", an SVG filter shows up, the text gets relief.`,
        story2_claude_b3: `"A bit more contrast on the edges", the highlight is adjusted accordingly.`,
        story2_claude_p3: `For SVG specifically, this changes everything. The final output (<code>boneV13.svg</code>, the one used in <a class="inline-link" href="workshop.html">the workshop</a>) is markedly richer: multi-stop linear gradient, diagonal texture pattern, edge highlight overlay, emboss filter on the text.`,
        story2_compare_title: "Both outputs, side by side",
        story2_compare_desc: "Same coords, same size, no retouching, just the SVG files each AI produced.",
        story2_evo_title: "Evolution of the bone",
        story2_evo_desc: `Thirteen versions total in the repo. Here are five chosen for their visual leap, same name, same palette, just to see what each iteration layers on.`,
        story2_evo_source_label: "SVG source, editable",
        story2_evo_tr_0: "Starting point: a simple pen trace. No fill, no text, just the silhouette to validate the shape.",
        story2_evo_tr_1: `v1 -> v4: the outline becomes a real bone shape and a "Name of the dog" placeholder appears. First sign this is going to become a tag.`,
        story2_evo_tr_2: "v4 -> v5: the outline turns solid, the interior is filled with a uniform metallic gradient, and the name reads clearly on top.",
        story2_evo_tr_3: "v5 -> v8: a diagonal texture pattern appears in the metal, and the name gets an SVG emboss effect (filter <feOffset>+<feGaussianBlur>+<feMerge>).",
        story2_evo_tr_4: "v8 -> v13: final polish. Edge highlight via a gradient overlay on the border, more contrasted outline, more believable shine. This is the version used in the workshop.",
        story2_evo_v1: "raw outline",
        story2_evo_v4: "name placeholder added",
        story2_evo_v5: "first metallic render",
        story2_evo_v8: "+ texture and emboss",
        story2_evo_v13: "final polish",
        story2_evo_outro: `Between v1 and v13 there's a lot of "live" tweaking, things like <em>"a bit more contrast on the edges"</em>, <em>"the metal should be darker, closer to the border"</em>, <em>"the name should look engraved into the metal"</em>. <small>(The actual chat logs are lost, these phrasings are reconstructions from the visible changes between versions.)</small> That's exactly the kind of iteration the artifact panel enables, see-and-correct loops in seconds.`,
        story2_gpt_raw_title: "Except eventually...",
        story2_gpt_raw_caption: "ChatGPT output, actual size, default palette.",
        story2_gpt_raw_p: "After several rounds of tweaking, the final result slowly inches toward what I had in mind, but I'm already fed up and decide to look elsewhere.",
        story2_anat_title: "Anatomy of a dogtag",
        story2_anat_desc: "The full dogtag, then zooms on each technique that builds it.",
        story2_anat_toggle: "Show markers",
        story2_anat_zoom_title: "Four techniques, in zoom",
        story2_card_grad_title: "The metallic gradient",
        story2_card_edge_title: "Edge highlight (2 paths)",
        story2_card_tex_title: "The texture pattern",
        story2_card_emboss_title: "The emboss filter (engraved text)",
        story2_card_reflet: "Highlight:",
        story2_card_ombre: "Shadow:",
        story2_card_metal: "Metal color:",
        story2_card_fond: "Background:",
        story2_card_diagonales: "Diagonals:",
        story2_card_reset: "Reset",
        story2_zoom_grad: `A diagonal <code>linearGradient</code> with <strong>8 stops</strong> instead of the usual 2-3. The sequence goes dark to light, dips back to mid, drops, then ends on the very light. That alternation is what creates the polished-metal illusion, eyes read the variations as reflections.`,
        story2_zoom_edge: `The bone is drawn <strong>twice</strong> on the same path. The first copy has the metallic fill and the dark border. The second, on top, has <em>no</em> fill, just a <code>stroke</code> painted with a white-to-transparent gradient. That double-pass simulates light catching the upper edge of the bone.`,
        story2_zoom_pattern: `A tiny <code>pattern</code> (2&times;5 units, infinite tile) with two faint diagonal crosses. From far away it gives the "brushed metal" feel without bloating the file, a single <code>&lt;pattern&gt;</code> element replaces thousands of tiny paths.`,
        story2_zoom_emboss: `The "engraved in metal" effect is an SVG filter chain: <code>feOffset</code> shifts a copy of the text's alpha, <code>feGaussianBlur</code> blurs it, <code>feFlood</code> + <code>feComposite</code> tints it semi-transparent black, and <code>feMerge</code> stacks the shadow <em>behind</em> the original text. Result: relief without redrawing the text.`,
        story2_anat_outro: `Combine those four techniques + a stroked circle for the photo + a JS calculation for the border color (the <a class="inline-link" href="story-part1.html">luminance flip from Act 1</a>), and you have a full dogtag. That's what gets rebuilt for each of the eleven dogs, change the name, the photo, the base color.`,
        story2_compare_gpt_meta: "1 path, 1 radial gradient, 3 color stops, 1 stroke. Clean but flat.",
        story2_compare_claude_meta: "Multi-stop gradient, diagonal texture pattern, edge-highlight gradient, emboss filter on the text. Richer.",
        story2_table_axis: "Criterion",
        story2_table_preview: "Live preview",
        story2_table_yes: "Yes (artifact)",
        story2_table_no: "No",
        story2_table_iter: "Visual iteration",
        story2_table_iter_gpt: "Text only",
        story2_table_iter_claude: "Change visible at every message",
        story2_table_complex: "Output complexity",
        story2_table_complex_gpt: "Simple, efficient",
        story2_table_complex_claude: "Richer by default",
        story2_table_edit: "Editing an existing file",
        story2_table_edit_gpt: "Via copy-paste",
        story2_table_edit_claude: "Via copy-paste (the web UI)",
        story2_js_title: "SVG + JavaScript = combo",
        story2_js_p1: "Once your SVG is text, you can manipulate it with any language. With a bit of JavaScript you can add, clone, animate or recolor elements in real time, without regenerating anything.",
        story2_js_p2: "Demo: a button that adds a dogtag with a random name and color. About a dozen lines of JS that clone the template, swap the text and palette, and insert it into the page.",
        story2_js_btn: "+ Add a dogtag",
        story2_js_reset: "Reset",
        story2_js_p3: `AI is exceptionally good at wiring these two worlds together. Describe in plain English "<em>a button that adds a new tag with a random name</em>", and get the right SVG, the right JavaScript, and the right CSS in one shot, that's what turns a static page into a living tool.`,
        story2_lesson_title: "The takeaway",
        story2_lesson_p1: `OK. Let's be honest: <strong>GPT was lamentable</strong> for this specific need. (It's also kind of funny to watch one company's AI try to defend a competitor's, so let's set the record straight.)`,
        story2_lesson_p2: `What matters is that <strong>good tools enable good results</strong>. SVG's text format lets you understand an image quickly and modify it directly with variables, exactly the way you would with code. Combine that with a tool that renders the code live (artifacts) or edits your files for you (Claude Code), and you go from "image generator" to "workshop".`,
        story2_lesson_p3: "The real win, in the end, isn't the generated code itself, it's the iteration loop.",
        story2_end_label: "End of Act 2",
        story2_end_continue: "Continue to Act 3 \u2192",
        // Gallery captions
        gallery_bone_v1: "Base icon (16x16)",
        gallery_bone_v2: "+ rotation (transform)",
        gallery_bone_v3: "+ matrix transform + text",
        gallery_bone_v4: "+ viewBox + layout",
        gallery_bone_v5: "+ gradients + filters",
        gallery_bone_v6: "+ highlight gradient",
        gallery_bone_v7: "+ refinements",
        gallery_bone_v8: "+ shadow & depth",
        gallery_bone_v9: "+ texture pattern",
        gallery_bone_v10: "+ edge effects",
        gallery_bone_v11: "+ text emboss filter",
        gallery_bone_v12: "+ polished styling",
        gallery_bone_v13: "Final: full metallic bone",
        gallery_blackthorn_desc: "Prunellier - CSS variables, defs/use pattern",
        gallery_blackthornv2_desc: "Variation with refined petals",
        gallery_rose_desc: "Complex petal layering with gradients",
        gallery_daisy_desc: "Symmetrical petal arrangement",
        gallery_bluebell_desc: "Bell-shaped flower with curves",
        gallery_pansy_desc: "Multi-colored petals with detail",
        gallery_wildrose_desc: "Progressive wild rose design",
        gallery_vine_desc: "Curved stroke with depth layers",
        gallery_ai_claude: "AI: Claude",
        gallery_ai_deepseek: "AI: DeepSeek",
        gallery_ai_gpt: "AI: ChatGPT",
        gallery_ai_gpt_bone: "AI: ChatGPT - bone tag variant",
        gallery_tool_cheat: "Shapes, paths, styling, transforms, filters",
        gallery_tool_bezier: "Quadratic & cubic bezier reference",
        gallery_tool_rotation: "Transform rotation demonstrations",
        gallery_tool_3dtext: "Advanced gradients for 3D text rendering",
        gallery_tool_patte: "Simple reusable decorative element",
        // Act 3 — story-part3.html
        story3_label: "Act 3",
        story3_hero_title: "Full SVG creation",
        story3_hero_subtitle: "What AI doesn't (yet) do on its own",
        story3_concept_title: "A card with two sides",
        story3_concept_p1: "Another project, another day. I wanted people to draw a tarot card. Problem: picking an AI-generated image directly felt like a shortcut. A card has two sides.",
        story3_concept_p2: "Logic: the front shows the arcana (AI-generated) and the card flips on click via a CSS 3D component. But what goes on the back? Another AI image? No, I wanted something personal, an SVG that could evolve with the user's choices.",
        story3_concept_p3: "AI is excellent at imagining the face. For the back I wanted to code a coherent visual language, reusable and parametric. Welcome to a 451-line SVG.",
        story3_card_title: "The card",
        story3_card_desc: `Play with the colors and the themes. Each theme redraws the four corners with a different ornament set: <strong>Flesh</strong> (organic), <strong>Matter</strong> (geometric) or <strong>Soul</strong> (mystical).`,
        story3_card_color_bg: "Background:",
        story3_card_color_pyramid: "Pyramid:",
        story3_card_color_eye: "Eye:",
        story3_card_color_edge: "Outline:",
        story3_card_theme: "Theme:",
        story3_card_theme_flesh: "Flesh",
        story3_card_theme_matter: "Matter",
        story3_card_theme_soul: "Soul",
        story3_card_reset: "Reset",
        story3_anat_title: "Anatomy of the card",
        story3_anat_desc: "Six SVG techniques that compose the card. Each stands on its own and combines with the others, that's what makes the format rich.",
        story3_card1_title: "CSS variables",
        story3_card1_desc: `A single <code>:root { }</code> inside the SVG exposes five colors. Anything that references <code>var(--color)</code> updates live, no regeneration.`,
        story3_card2_title: "&lt;defs&gt; and &lt;use&gt;",
        story3_card2_desc: `A shape is defined once in <code>&lt;defs&gt;</code> then instantiated with <code>&lt;use href="#id"&gt;</code> and a different transform. The same brick, ray or triangle is reused dozens of times without inflating the file.`,
        story3_card3_title: "Gradients",
        story3_card3_desc: "Four layered gradients (radial for the iris and sclera, linear for the ornaments) build the depth. The iris alone combines 3 stops with varying opacities.",
        story3_card4_title: "Animated filters",
        story3_card4_desc: `<code>feGaussianBlur</code> + <code>feMerge</code> chains produce the halo. A SMIL <code>&lt;animate&gt;</code> element cycles the <code>stdDeviation</code> value between 2 and 7 over 3 seconds, on loop.`,
        story3_card5_title: "Clip paths",
        story3_card5_desc: `The pyramid is a triangle filled with rectangular bricks. A triangular <code>&lt;clipPath&gt;</code> cuts off the bricks that overflow: draw dumb rectangles, let the clip do the rest.`,
        story3_card6_title: "Symmetry via transform",
        story3_card6_desc: `One corner ornament is drawn once, then mirrored to the other three with <code>scale(-1,1)</code>, <code>scale(1,-1)</code>, <code>scale(-1,-1)</code>. Change one corner, all four follow.`,
        story3_animated_title: "What if we animated it?",
        story3_animated_desc: "Same card, with a few CSS animations layered on: a slow rotation on the ray pattern, a hue drift on the palette, a subtle levitation. SVG is text that can do anything.",
        story3_license: "\u00a9 Simon Bedard. SVG shared for educational purposes. Commercial use prohibited.",
        story3_end_label: "End of Act 3",
        story3_end_p: "That's it. Three acts, one thread: AI helps build, but design decisions stay human.",
        story3_end_continue: "Go to the workshop \u2192",
        // Stories index entry for Act 3
        stories_act3_title: "Act 3: Full SVG creation",
        stories_act3_desc: "When AI alone isn't enough: anatomy of a hand-written 451-line SVG — variables, defs/use, animated filters, clip paths, symmetry.",
    }
};

let currentLang = 'fr';

function detectLanguage() {
    const saved = localStorage.getItem('svg-conf-lang');
    if (saved) return saved;
    const browserLang = navigator.language || navigator.userLanguage;
    return browserLang.startsWith('fr') ? 'fr' : 'en';
}

function setLanguage(lang) {
    currentLang = lang;
    localStorage.setItem('svg-conf-lang', lang);
    document.documentElement.lang = lang;
    translatePage();
    const btn = document.querySelector('.lang-toggle');
    if (btn) btn.textContent = lang === 'fr' ? 'EN' : 'FR';
    // Let page-specific widgets (carousels, narration, etc.) re-read
    // translations that live outside data-i18n attributes.
    document.dispatchEvent(new CustomEvent('langchange', { detail: { lang } }));
}

function toggleLanguage() {
    setLanguage(currentLang === 'fr' ? 'en' : 'fr');
}

function t(key) {
    return translations[currentLang][key] || translations['en'][key] || key;
}

function translatePage() {
    document.querySelectorAll('[data-i18n]').forEach(el => {
        const key = el.getAttribute('data-i18n');
        const text = t(key);
        if (text) el.textContent = text;
    });
    document.querySelectorAll('[data-i18n-html]').forEach(el => {
        const key = el.getAttribute('data-i18n-html');
        const text = t(key);
        if (text) el.innerHTML = text;
    });
    document.querySelectorAll('[data-i18n-placeholder]').forEach(el => {
        const key = el.getAttribute('data-i18n-placeholder');
        const text = t(key);
        if (text) el.placeholder = text;
    });
}

/* ===== Header & Footer Loading ===== */
async function loadPartials() {
    try {
        const headerResp = await fetch('parts/header.html');
        if (headerResp.ok) {
            document.getElementById('header-placeholder').innerHTML = await headerResp.text();
        }
    } catch (e) { /* header already inline */ }

    try {
        const footerResp = await fetch('parts/footer.html');
        if (footerResp.ok) {
            document.getElementById('footer-placeholder').innerHTML = await footerResp.text();
        }
    } catch (e) { /* footer already inline */ }

    // Mark active nav link
    const currentPage = window.location.pathname.split('/').pop() || 'index.html';
    document.querySelectorAll('nav a').forEach(a => {
        const href = a.getAttribute('href');
        if (href === currentPage || (currentPage === '' && href === 'index.html')) {
            a.classList.add('active');
        }
    });

    // Hamburger toggle
    const hamburger = document.querySelector('.hamburger');
    const nav = document.querySelector('nav');
    if (hamburger && nav) {
        hamburger.addEventListener('click', () => nav.classList.toggle('open'));
    }

    // Lang toggle
    const langBtn = document.querySelector('.lang-toggle');
    if (langBtn) langBtn.addEventListener('click', toggleLanguage);

    // Apply translations
    setLanguage(detectLanguage());
}

/* ===== Tabs ===== */
function initTabs() {
    document.querySelectorAll('.tabs').forEach(tabBar => {
        const buttons = tabBar.querySelectorAll('.tab-btn');
        const container = tabBar.parentElement;
        const contents = container.querySelectorAll('.tab-content');

        buttons.forEach(btn => {
            btn.addEventListener('click', () => {
                buttons.forEach(b => b.classList.remove('active'));
                contents.forEach(c => c.classList.remove('active'));
                btn.classList.add('active');
                const target = container.querySelector(`#${btn.dataset.tab}`);
                if (target) target.classList.add('active');
            });
        });
    });
}

/* ===== Init ===== */
document.addEventListener('DOMContentLoaded', () => {
    loadPartials();
    initTabs();
});
